'use strict';

module.exports = {
  GOOGLE_API_CLIENT_ID: process.env.GOOGLE_API_CLIENT_ID,
  GOOGLE_API_CLIENT_SECRET: process.env.GOOGLE_API_CLIENT_SECRET,
  FORECAST_ACCOUNT_ID: process.env.FORECAST_ACCOUNT_ID,
  FORECAST_AUTHORIZATION: process.env.FORECAST_AUTHORIZATION,
  BASE_URL: process.env.BASE_URL
};
